language: android
android:
  components:
    - tools
    - build-tools-26.0.2
    - android-26
    - extra-android-m2repository
    - extra-android-support

before_install:
  - chmod +x ./VirtualApp/gradlew

script:
  - cd VirtualApp
  - ./gradlew assembleRelease
